In [8]:
import json
import pandas as pd
from pathlib import Path

def find_project_root():
    here = Path.cwd().parent
    for folder in [here, *here.parents]:
        if (folder / "requirements.txt").exists() or (folder / ".git").exists():
            return folder
        return here

PROJECT_ROOT = find_project_root()
print(PROJECT_ROOT)
BOOTSTRAP_FILEPATH = PROJECT_ROOT / "data" / "raw" / "bootstrap-static.json"
with open(BOOTSTRAP_FILEPATH,"r",encoding="utf-8") as f:
    bootstrap = json.load(f)
    
FIXTURES_FILEPATH = PROJECT_ROOT / "data" / "raw" / "fixtures.json"
with open(FIXTURES_FILEPATH,"r",encoding="utf-8") as f:
    fixtures = json.load(f)
    
players = pd.json_normalize(bootstrap["elements"])
teams = pd.json_normalize(bootstrap["teams"])
events = pd.json_normalize(bootstrap["events"])
fixtures_df = pd.json_normalize(fixtures)

players.head()

d:\fpl-edge

,can_transact,can_select,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,price_change_percent,...,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90,defensive_contribution_per_90
0,True,True,NaN,None,154561,0,0,0,0,0,...,1,472,64,32,3,5,1,1.00,0.51,0.00
1,True,True,NaN,None,109745,0,0,0,0,0,...,8,206,49,285,28,403,45,1.00,0.00,0.00
2,True,True,NaN,None,437495,0,0,0,0,0,...,14,270,55,515,63,486,58,0.00,0.00,0.00
3,True,True,NaN,None,226597,0,0,0,0,0,...,1,568,188,4,1,7,1,0.98,0.59,9.07
4,True,True,0.0,None,445122,0,0,0,0,0,...,3,539,186,13,3,282,107,1.03,0.48,5.43

In [9]:
players.columns

Index(['can_transact', 'can_select', 'chance_of_playing_next_round',
       'chance_of_playing_this_round', 'code', 'cost_change_event',
       'cost_change_event_fall', 'cost_change_start', 'cost_change_start_fall',
       'price_change_percent',
       ...
       'now_cost_rank_type', 'form_rank', 'form_rank_type',
       'points_per_game_rank', 'points_per_game_rank_type', 'selected_rank',
       'selected_rank_type', 'starts_per_90', 'clean_sheets_per_90',
       'defensive_contribution_per_90'],
      dtype='str', length=105)

In [10]:
teams.head()

,code,draw,form,id,loss,name,played,points,position,short_name,...,unavailable,win,link_url,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
0,3,0,None,1,0,Arsenal,0,0,0,ARS,...,False,0,,4,5,0,0,0,0,1
1,7,0,None,2,0,Aston Villa,0,0,0,AVL,...,False,0,,3,4,0,0,0,0,2
2,91,0,None,3,0,Bournemouth,0,0,0,BOU,...,False,0,,3,3,0,0,0,0,127
3,94,0,None,4,0,Brentford,0,0,0,BRE,...,False,0,,3,3,0,0,0,0,130
4,36,0,None,5,0,Brighton,0,0,0,BHA,...,False,0,,2,3,0,0,0,0,131

In [11]:
fixtures_df.head()

,code,event,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,started,team_a,team_a_score,team_h,team_h_score,stats,team_h_difficulty,team_a_difficulty,pulse_id
0,2645195,1,False,False,1,2026-08-21T19:00:00Z,0,False,False,7,None,1,None,[],2,5,0
1,2645198,1,False,False,4,2026-08-22T11:30:00Z,0,False,False,16,None,11,None,[],4,2,0
2,2645197,1,False,False,3,2026-08-22T14:00:00Z,0,False,False,8,None,9,None,[],3,3,0
3,2645199,1,False,False,5,2026-08-22T14:00:00Z,0,False,False,20,None,12,None,[],2,2,0
4,2645200,1,False,False,6,2026-08-22T14:00:00Z,0,False,False,13,None,18,None,[],2,3,0

In [12]:
events.head()

,id,name,deadline_time,release_time,average_entry_score,finished,data_checked,highest_scoring_entry,deadline_time_epoch,deadline_time_game_offset,...,chip_plays,most_selected,most_transferred_in,top_element,top_element_info,transfers_made,most_captained,most_vice_captained,overrides.element_types,overrides.pick_multiplier
0,1,Gameweek 1,2026-08-21T17:30:00Z,None,0,False,False,None,1787333400,0,...,[],None,None,None,None,0,None,None,[],None
1,2,Gameweek 2,2026-08-28T17:30:00Z,None,0,False,False,None,1787938200,0,...,[],None,None,None,None,0,None,None,[],None
2,3,Gameweek 3,2026-09-04T17:30:00Z,None,0,False,False,None,1788543000,0,...,[],None,None,None,None,0,None,None,[],None
3,4,Gameweek 4,2026-09-12T12:30:00Z,None,0,False,False,None,1789216200,0,...,[],None,None,None,None,0,None,None,[],None
4,5,Gameweek 5,2026-09-18T17:30:00Z,None,0,False,False,None,1789752600,0,...,[],None,None,None,None,0,None,None,[],None

In [7]:
import pandas as pd
from pathlib import Path

def find_project_root():
    here = Path.cwd().parent
    for folder in [here, *here.parents]:
        if (folder / "requirements.txt").exists() or (folder / ".git").exists():
            return folder
        return here


PROJECT_ROOT = find_project_root()
print(PROJECT_ROOT)
df = pd.read_csv(PROJECT_ROOT/"data"/"processed"/"projections.csv")
top = df.sort_values("projected_points", ascending=False)[
    ["id", "web_name", "team_short_name", "position"]
]
print(top.head(10).to_string(index=False))

d:\fpl-edge
 id web_name team_short_name position
427   Mbeumo             MUN      MID
379     Isak             LIV      FWD
154   Palmer             CHE      MID
490     Wood             NFO      FWD
 55  Watkins             AVL      FWD
428    Cunha             MUN      MID
411  Haaland             MCI      FWD
464    Wissa             NEW      FWD
457 J.Murphy             NEW      MID
 70 Kluivert             BOU      MID

In [4]:
import pandas as pd
from pathlib import Path


def find_project_root():
    here = Path.cwd().parent
    for folder in [here, *here.parents]:
        if (folder / "requirements.txt").exists() or (folder / ".git").exists():
            return folder
        return here


PROJECT_ROOT = find_project_root()
print(PROJECT_ROOT)
df = pd.read_csv(PROJECT_ROOT / "data" / "processed" / "projections.csv")

print(df[["web_name", "projected_points", "form", "points_per_game"]].head())

d:\fpl-edge
      web_name  projected_points  form  points_per_game
0  B.Fernandes             78.29   0.0              6.7
1      Haaland             62.50   0.0              6.8
2         Enzo             54.24   0.0              4.4
3   Szoboszlai             53.50   0.0              4.4
4      Semenyo             53.19   0.0              5.5